### ISSUE TITLE
Regarding issue 58

### ISSUE THREAD

**Issue by ItsEddie** [babelshift/SteamWebAPI2#67] opened 2018-10-19 06:45 UTC
This has not been resolved yet as I'm currently experiencing the same problem as him. This is about [this issue](https://github.com/babelshift/SteamWebAPI2/issues/58).

**Comment by babelshift** [comment] 2018-10-19 13:48
Closing as a duplicate of #58.

**Closed by babelshift** 2018-10-19 13:48 UTC
