### ISSUE TITLE
Steam User login pass dev key

### ISSUE THREAD

**Issue by kyilintun2017** [babelshift/SteamWebAPI2#75] opened 2019-10-16 04:52 UTC
can't use this function.
var steamInterface = new SteamUser("<devKeyHere>");
the class has
SteamUser(ISteamWebRequest steamWebRequest, ISteamWebInterface steamWebInterface = null);

Please kindly give advise.

Error message: Cannot convert from 'string' to 'SteamWebAPI2.Utilities.ISteamWebRequest'

**Comment by kyilintun2017** [comment] 2019-10-18 06:45
No longer needed.

**Comment by babelshift** [comment] 2019-10-18 20:42
Duplicate of #74

**Comment by babelshift** [comment] 2019-10-18 21:15
Fixed by #76

**Closed by babelshift** 2019-10-18 21:15 UTC
Labels: duplicate
